// Code generated by entc, DO NOT EDIT.

package ent

import (
	"reader/internal/book/data/ent/book"
	"reader/internal/book/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookFields[0].Descriptor()
	// book.IDValidator is a validator for the "id" field. It is called by the builders before save.
	book.IDValidator = bookDescID.Validators[0].(func(int64) error)
}
