// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"reader/internal/account/biz"
	"reader/internal/account/data"
	"reader/internal/account/service"
)

// Injectors from wire.go:

func NewAccountService() (*service.AccountService, func(), error) {
	client, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(client)
	accountUseCase := biz.NewAccountUseCase(accountRepo)
	accountService := service.NewAccountService(accountUseCase)
	return accountService, func() {
		cleanup()
	}, nil
}
