// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"reader/internal/book/biz"
	"reader/internal/book/data"
	"reader/internal/book/service"
)

// Injectors from wire.go:

func NewBookService() (*service.BookService, func(), error) {
	client, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	bookRepo := data.NewBookRepo(client)
	bookUseCase := biz.NewBookUseCase(bookRepo)
	bookService := service.NewBookService(bookUseCase)
	return bookService, func() {
		cleanup()
	}, nil
}
